Traceback (most recent call last):
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
vals1.sum()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [4][0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m [43mvals1[49m[38;5;241;43m.[39;49m[43msum[49m[43m([49m[43m)[49m

File [0;32m/Volumes/GoogleDrive/æˆ‘çš„é›²ç«¯ç¡¬ç¢Ÿ/0. codepool_python/python_ds/python_ds_env/lib/python3.8/site-packages/numpy/core/_methods.py:48[0m, in [0;36m_sum[0;34m(a, axis, dtype, out, keepdims, initial, where)[0m
[1;32m     46[0m [38;5;28;01mdef[39;00m [38;5;21m_sum[39m(a, axis[38;5;241m=[39m[38;5;28;01mNone[39;00m, dtype[38;5;241m=[39m[38;5;28;01mNone[39;00m, out[38;5;241m=[39m[38;5;28;01mNone[39;00m, keepdims[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m     47[0m          initial[38;5;241m=[39m_NoValue, where[38;5;241m=[39m[38;5;28;01mTrue[39;00m):
[0;32m---> 48[0m     [38;5;28;01mreturn[39;00m [43mumr_sum[49m[43m([49m[43ma[49m[43m,[49m[43m [49m[43maxis[49m[43m,[49m[43m [49m[43mdtype[49m[43m,[49m[43m [49m[43mout[49m[43m,[49m[43m [49m[43mkeepdims[49m[43m,[49m[43m [49m[43minitial[49m[43m,[49m[43m [49m[43mwhere[49m[43m)[49m

[0;31mTypeError[0m: unsupported operand type(s) for +: 'int' and 'NoneType'
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

