Traceback (most recent call last):
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/hanklee/.pyenv/versions/3.8.0/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.imshow(Z, extent=[0, 5, 0, 5], origin='lower',
           cmap='RdGy')
plt.colorbar()
plt.axis(aspect='image');
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [7][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m plt[38;5;241m.[39mimshow(Z, extent[38;5;241m=[39m[[38;5;241m0[39m, [38;5;241m5[39m, [38;5;241m0[39m, [38;5;241m5[39m], origin[38;5;241m=[39m[38;5;124m'[39m[38;5;124mlower[39m[38;5;124m'[39m,
[1;32m      2[0m            cmap[38;5;241m=[39m[38;5;124m'[39m[38;5;124mRdGy[39m[38;5;124m'[39m)
[1;32m      3[0m plt[38;5;241m.[39mcolorbar()
[0;32m----> 4[0m [43mplt[49m[38;5;241;43m.[39;49m[43maxis[49m[43m([49m[43maspect[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mimage[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/Volumes/GoogleDrive/æˆ‘çš„é›²ç«¯ç¡¬ç¢Ÿ/0. codepool_python/python_ds/python_ds_env/lib/python3.8/site-packages/matplotlib/pyplot.py:2361[0m, in [0;36maxis[0;34m(emit, *args, **kwargs)[0m
[1;32m   2359[0m [38;5;129m@_copy_docstring_and_deprecators[39m(Axes[38;5;241m.[39maxis)
[1;32m   2360[0m [38;5;28;01mdef[39;00m [38;5;21maxis[39m([38;5;241m*[39margs, emit[38;5;241m=[39m[38;5;28;01mTrue[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m-> 2361[0m     [38;5;28;01mreturn[39;00m [43mgca[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43maxis[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[43memit[49m[38;5;241;43m=[39;49m[43memit[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/Volumes/GoogleDrive/æˆ‘çš„é›²ç«¯ç¡¬ç¢Ÿ/0. codepool_python/python_ds/python_ds_env/lib/python3.8/site-packages/matplotlib/axes/_base.py:2094[0m, in [0;36m_AxesBase.axis[0;34m(self, emit, *args, **kwargs)[0m
[1;32m   2092[0m     [38;5;28mself[39m[38;5;241m.[39mset_ylim(ymin, ymax, emit[38;5;241m=[39memit, auto[38;5;241m=[39myauto)
[1;32m   2093[0m [38;5;28;01mif[39;00m kwargs:
[0;32m-> 2094[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124maxis() got an unexpected keyword argument [39m[38;5;124m"[39m
[1;32m   2095[0m                     [38;5;124mf[39m[38;5;124m"[39m[38;5;124m'[39m[38;5;132;01m{[39;00m[38;5;28mnext[39m([38;5;28miter[39m(kwargs))[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m"[39m)
[1;32m   2096[0m [38;5;28;01mreturn[39;00m ([38;5;241m*[39m[38;5;28mself[39m[38;5;241m.[39mget_xlim(), [38;5;241m*[39m[38;5;28mself[39m[38;5;241m.[39mget_ylim())

[0;31mTypeError[0m: axis() got an unexpected keyword argument 'aspect'
TypeError: axis() got an unexpected keyword argument 'aspect'

